version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: vault-postgres
    environment:
      POSTGRES_DB: vaultdb
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vaultpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vault -d vaultdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vault-redis
    command: redis-server --appendonly yes --requirepass devredis
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "devredis", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata:
  redisdata:
  
